openapi: 3.0.9
info:
  description: |- 
    This Web API contains the specification of microservices providing support for converting 
    NPY files into JSON format. This functionality is intended to be used in the EDScorbot front-end. 

    The documentation about the routes are available individually. 
    
    Some useful links:
    - This server has been developed using [Flask](https://readthedocs.org/projects/flask) - a lightweight WSGI web application framework
    - [EDScorbot Python microservice](https://github.com/adalbertocajueiro/edscorbot-py) - a Python implementation 
    of this Web API used in the EDScorbot project and available for download.

  version: "1.0.0"
  title: "EDScorbot Python API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "adalberto@computacao.ufcg.edu.br"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
    - url: "http://192.168.1.104"
      description: Development and test environments 

tags:
  - name: file_manipulation
    description: Functions for manipulating NPY files
    
paths:
  /python/load:
    post:
      tags:
        - file_manipulation
      operationId: loadFile
      summary: Loads the content of a NPY file
      description: It loads the content of a NPY file and returns it as a list of points
        in a JSON object.

      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                
      responses:
        200:
          description: Load content success
          content:
            application/octet-stream:
              schema:
                example:
                  [
                    [1,1,1,1,1,1,200],
                    [2,2,2,2,2,2,200]
                  ] 
             
        500:
          description: Some other internal error occurred in the server 
          content:
            application/json:
              schema:
                example: 
                  message: Translation error
                  status: internal server error
  /python/convert:
    post:
      tags:
      - file_manipulation
      operationId: convertFile
      summary: Converts the content of an array of points
      description: It converts the content of an array of points and returns it as a list of points in a JSON object.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                content:
                  type: string
                sourceType:
                  type: string
                targetType:
                  type: string
                hasTimeInfo:
                  type: boolean
                robotName:
                  type: string
                
      responses:
        200:
          description: Translation success
          content:
            application/octet-stream:
              schema:
                example:
                  [
                    [1,1,1,1,1,1,200],
                    [2,2,2,2,2,2,200]
                  ] 
             
        500:
          description: Some other internal error occurred in the server 
          content:
            application/json:
              schema:
                example: 
                  message: Translation error
                  status: internal server error